owner: kzshantonu
repo: instances

sites:
  - name: nttr.stream
    url: https://nttr.stream
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: leddit.xyz
    url: https://leddit.xyz
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/us.png
  - name: de.nttr.stream
    url: https://de.nttr.stream
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: de.leddit.xyz
    url: https://de.leddit.xyz
    icon: https://raw.githubusercontent.com/kreativekorp/vexillo/master/artwork/vexillo/pvb160/de.png
  - name: send
    url: https://send.mni.li
    icon: https://raw.githubusercontent.com/timvisee/send/master/assets/icon.svg
status-website:
  cname: instances.kazi.one
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
