owner: kzshantonu
repo: instances

sites:
  - name: nttr.stream
    url: https://nttr.stream
  - name: leddit.xyz
    url: https://leddit.xyz
  - name: DoT
    check: "tcp-ping"
    url: $U1
    port: 853
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

status-website:
  cname: instances.kazi.one
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: dark
