owner: kzshantonu
repo: instances

sites:
  - name: Nitter instance
    url: https://nttr.stream
  - name: Libreddit instance
    url: https://leddit.xyz

status-website:
  theme: dark
  cname: instances.kazi.one
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "Upptime is the open-source uptime monitor and status page, powered entirely by GitHub"
  introMessage: "[Get your own for free](https://github.com/upptime/upptime)"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
